version: '3.3'
services:
  ui:
      container_name: ui
      image: registry.bavenir.eu/cell_towers_coverage_ui:dev
      ports:
          - 4200:4200
  app:
      container_name: app
      image: registry.bavenir.eu/cell_towers_coverage:dev
      ports:
          - 8080:8080
  postgis:
      container_name: postgis
      environment:
          - POSTGRES_PASSWORD=test
          - POSTGRES_USER=postgres
      image: postgis/postgis:15-3.3-alpine
      volumes:
        - pgdata:/var/lib/postgresql/data
      ports:
          - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@bavenir.eu
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:
  